# Generated by Django 4.2.11 on 2025-08-29 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=256)),
                ('text', models.CharField(default='', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt_app.question')),
            ],
        ),
    ]
